/**
 * GENERATED FILE — do not edit.
 *
 * Generated by scripts/gen-font-tables.mjs from the pdfrx example's
 * google_fonts_resolver.dart. Re-run the script when the upstream tables
 * change. Each entry is a downloadable Google Fonts TTF identified by the
 * SHA-256 hash used by fonts.gstatic.com (https://fonts.gstatic.com/s/a/<hash>.ttf).
 */

export interface GoogleFontsFile {
  /** Compact Google Fonts family name (e.g. 'NotoSansJP'). */
  faceName: string;
  /** CSS font weight of this file. */
  weight: number;
  /** SHA-256 digest; also the fonts.gstatic.com file name. */
  hash: string;
  /** Expected byte length. */
  length: number;
}

export type WeightTable = Record<number, GoogleFontsFile>;

export const arimo: WeightTable = {
  400: { faceName: 'Arimo', weight: 400, hash: 'dbc3f5256cfcb1aa62736daaab3bea7dc85c7c68028cd408671a796537da3a0e', length: 315684 },
  500: { faceName: 'Arimo', weight: 500, hash: 'a853459fe429fbc56342801939f6abd1bd18700830e2f34895d3ea74cf90ed56', length: 318660 },
  600: { faceName: 'Arimo', weight: 600, hash: '4c91b9aff501566727a4386c973afa730f2ca6af63776681e73bbefb062c86ab', length: 319656 },
  700: { faceName: 'Arimo', weight: 700, hash: 'ae8ae33dbafc8b8759404c8f812d36fe44067f5c6b90b38495a2be5daa57c5da', length: 316204 },
};

export const arimoItalic: WeightTable = {
  400: { faceName: 'Arimo', weight: 400, hash: '963985e80cf691a33ca6b4879232d4b34d3f8f631f0c6353d60a1595a519a6bf', length: 337860 },
  500: { faceName: 'Arimo', weight: 500, hash: '393deb90793814a70d0bdcbbf8e1c16c3f86fa348de25b6f915b12f86a284e75', length: 342400 },
  600: { faceName: 'Arimo', weight: 600, hash: '15fd3e30d1fcc180ad52f205cb4d1e56a2ee66633ffb716a034a2d522cd6be3b', length: 342948 },
  700: { faceName: 'Arimo', weight: 700, hash: '4232c2585c5833abe3d7e3adb1dc11dd367cdeefd26135499eb04c5d2c697096', length: 339292 },
};

export const tinos: WeightTable = {
  400: { faceName: 'Tinos', weight: 400, hash: '23e68bc98222339eb30959aade856a732c4f3ea04e5c229e00cede6c5378c2ed', length: 246568 },
  700: { faceName: 'Tinos', weight: 700, hash: '1072711f4d2e7b23ff31277fde58d4b1dfd846d0a31410102b39aa8a95943b84', length: 240620 },
};

export const tinosItalic: WeightTable = {
  400: { faceName: 'Tinos', weight: 400, hash: '1751ba26644fb09379dcddda6f5c0065988cf041859f8027ef182b99ba145c22', length: 248184 },
  700: { faceName: 'Tinos', weight: 700, hash: 'b951c5c411f9fb34b0f43af03345658f01741e07d1f73b23bf1e4b68e278729c', length: 246184 },
};

export const cousine: WeightTable = {
  400: { faceName: 'Cousine', weight: 400, hash: '61e63301fbd450ae3f676d08d4a39db8cd7f6429228059d91a54ef5cfa301e81', length: 184164 },
  700: { faceName: 'Cousine', weight: 700, hash: 'dd86d125d0156720f2d7aef7937c0890fcd1a4e7fc29fdf338ed961eb34786ad', length: 183872 },
};

export const cousineItalic: WeightTable = {
  400: { faceName: 'Cousine', weight: 400, hash: '6de5bb27b76b4b29eb42d2ea03df4acd247c44412587c0dcac88af24d807c9af', length: 192900 },
  700: { faceName: 'Cousine', weight: 700, hash: '8f58007ae958dd130181ed73cd8e9e683443b15c9cff60f3cb5213a1c5b18792', length: 191964 },
};

export const notoSans: WeightTable = {
  100: { faceName: 'NotoSans', weight: 100, hash: 'bc6ceb177561b27cfb9123c0dd372a54774cb6bcebe4ce18c12706bbb7ee902c', length: 523812 },
  200: { faceName: 'NotoSans', weight: 200, hash: '807ad06b65dbbaf657e4a7dcb6d2b0734c8831cd21a1f9172387ad0411cc396f', length: 524708 },
  300: { faceName: 'NotoSans', weight: 300, hash: '4e3e9bb50c6e6ade7e4a491bf0033d6b6ec3326a2621834201e735691cec4968', length: 524492 },
  400: { faceName: 'NotoSans', weight: 400, hash: '725edd9b341324f91a3859e24824c455d43c31be72ca6e710acd0f95920d61ee', length: 523940 },
  500: { faceName: 'NotoSans', weight: 500, hash: 'a77c7c7a4d75c23c5e68bcff3d44f71eb1ec0f80fe245457053ea43a4ce61bd4', length: 524252 },
  600: { faceName: 'NotoSans', weight: 600, hash: 'fc5b5ba2d400f44b0686c46db557e6b8067a97ade7337f14f823f524675c038c', length: 524444 },
  700: { faceName: 'NotoSans', weight: 700, hash: '222685dcf83610e3e88a0ecd4c602efde7a7b832832502649bfe2dcf1aa0bf15', length: 523772 },
  800: { faceName: 'NotoSans', weight: 800, hash: 'c6e87f6834db59a2a64ce43dce2fdc1aa3441f2a23afb0bfd667621403ed688c', length: 524672 },
  900: { faceName: 'NotoSans', weight: 900, hash: '7ead4fec44c3271cf7dc5d9f74795eb05fa9fb3cedc7bde3232eb10573d5f6cd', length: 524708 },
};

export const notoSansItalic: WeightTable = {
  100: { faceName: 'NotoSans-Italic', weight: 100, hash: '8b32677abe42a47cdade4998d4124a3e1b44efa656c5badf27de546768c82f0d', length: 541316 },
  200: { faceName: 'NotoSans-Italic', weight: 200, hash: 'd64c291d542bb1211538aa1448a7f6bbaca4dbd170e78b8b8242be5c9ff28959', length: 541752 },
  300: { faceName: 'NotoSans-Italic', weight: 300, hash: '3a902e6bbe1ffba43428cb2981f1185ef529505836c311af5f6e5690bf9b44c8', length: 541688 },
  400: { faceName: 'NotoSans-Italic', weight: 400, hash: '3d23478749575c0febb6169fc3dba6cb8cdb4202e8fb47ae1867c71a21792295', length: 539972 },
  500: { faceName: 'NotoSans-Italic', weight: 500, hash: '085819a42ab67069f29329ae066ff8206a4b518bf6496dbf1193284f891fdbd1', length: 540456 },
  600: { faceName: 'NotoSans-Italic', weight: 600, hash: 'ecb66a73df07fac622c73fdc0e4972bd51f50165367807433d7fc620378f9577', length: 540608 },
  700: { faceName: 'NotoSans-Italic', weight: 700, hash: 'f72d0f7c9c7279b2762017fbafa2bcd9aaccdf7a79b8cf686f874e2eeb0e51ce', length: 540016 },
  800: { faceName: 'NotoSans-Italic', weight: 800, hash: '0ef3e94eb6875007204e41604898141fa5104f7e20b87cb5640509a8f10430b5', length: 540812 },
  900: { faceName: 'NotoSans-Italic', weight: 900, hash: 'b0e0148ef878a4ca6a295b6b56b1bfb4773400ff8ee0a31a1338285725dd514f', length: 540396 },
};

export const notoSansSc: WeightTable = {
  100: { faceName: 'NotoSansSC', weight: 100, hash: 'f1b8c2a287d23095abd470376c60519c9ff650ae8744b82bf76434ac5438982a', length: 10538940 },
  200: { faceName: 'NotoSansSC', weight: 200, hash: 'cba9bb657b61103aeb3cd0f360e8d3958c66febf59fbf58a4762f61e52015d36', length: 10544320 },
  300: { faceName: 'NotoSansSC', weight: 300, hash: '4cdbb86a1d6eca92c7bcaa0c759593bc2600a153600532584a8016c24eaca56c', length: 10545812 },
  400: { faceName: 'NotoSansSC', weight: 400, hash: 'eacedb2999b6cd30457f3820f277842f0dfbb28152a246fca8161779a8945425', length: 10540772 },
  500: { faceName: 'NotoSansSC', weight: 500, hash: '5383032c8e54fc5fa09773ce16483f64d9cdb7d1f8e87073a556051eb60f8529', length: 10533968 },
  600: { faceName: 'NotoSansSC', weight: 600, hash: '85c00dac0627c2c0184c24669735fad5adbb4f150bcb320c05620d46ed086381', length: 10530476 },
  700: { faceName: 'NotoSansSC', weight: 700, hash: 'a7a29b6d611205bb39b9a1a5c2be5a48416fbcbcfd7e6de98976e73ecb48720b', length: 10530536 },
  800: { faceName: 'NotoSansSC', weight: 800, hash: '038de57b1dc5f6428317a8b0fc11984789c25f49a9c24d47d33d2c03e3491d28', length: 10525556 },
  900: { faceName: 'NotoSansSC', weight: 900, hash: '501582a5e956ab1f4d9f9b2d683cf1646463eea291b21f928419da5e0c5a26eb', length: 10521812 },
};

export const notoSansTc: WeightTable = {
  100: { faceName: 'NotoSansTC', weight: 100, hash: '53debc0456f3a7d4bdb00e14704fc29ea129d38bd8a9f6565cf656ddc27abb91', length: 7089040 },
  200: { faceName: 'NotoSansTC', weight: 200, hash: '5ef06c341be841ab9e166a9cc7ebc0e39cfe695da81d819672f3d14b3fca56a8', length: 7092508 },
  300: { faceName: 'NotoSansTC', weight: 300, hash: '9e50ec0d5779016c848855daa73f8d866ef323f0431d5770f53b60a1506f1c4a', length: 7092872 },
  400: { faceName: 'NotoSansTC', weight: 400, hash: 'b4f9cfdee95b77d72fe945347c0b7457f1ffc0d5d05eaf6ff688e60a86067c95', length: 7090948 },
  500: { faceName: 'NotoSansTC', weight: 500, hash: '2011294f66de6692639ee00a9e74d67bc9134f251100feb5448ab6322a4a2a75', length: 7087068 },
  600: { faceName: 'NotoSansTC', weight: 600, hash: '440471acbbc2a3b33bf11befde184b2cafe5b0fcde243e2b832357044baa4aa1', length: 7084432 },
  700: { faceName: 'NotoSansTC', weight: 700, hash: '22779de66d31884014b0530df89e69d596018a486a84a57994209dff1dcb97cf', length: 7085728 },
  800: { faceName: 'NotoSansTC', weight: 800, hash: 'f5e8e3e746319570b0979bfa3a90b6ec6a84ec38fe9e41c45a395724c31db7b4', length: 7082400 },
  900: { faceName: 'NotoSansTC', weight: 900, hash: '2b1ab3d7db76aa94006fa19dc38b61e93578833d2e3f268a0a3b0b1321852af6', length: 7079980 },
};

export const notoSansJp: WeightTable = {
  100: { faceName: 'NotoSansJP', weight: 100, hash: '78a1fa1d16c437fe5d97df787782b6098a750350b5913b9f80089dc81f512417', length: 5706804 },
  200: { faceName: 'NotoSansJP', weight: 200, hash: 'c0532e4abf0ca438ea0e56749a3106a5badb2f10a89c8ba217b43dae4ec6e590', length: 5708144 },
  300: { faceName: 'NotoSansJP', weight: 300, hash: '64f10b3b9e06c99b76b16e1441174fba6adf994fcd6b8036cef2fbfa38535a84', length: 5707688 },
  400: { faceName: 'NotoSansJP', weight: 400, hash: '209c70f533554d512ef0a417b70dfe2997aeec080d2fe41695c55b361643f9ba', length: 5703748 },
  500: { faceName: 'NotoSansJP', weight: 500, hash: 'c5233cdc5a2901be5503f0d95ff48b4b5170afff6a39f95a076520cb73f17860', length: 5700280 },
  600: { faceName: 'NotoSansJP', weight: 600, hash: '852ad9268beb7d467374ec5ff0d416a22102c52d984ec21913f6d886409b85c4', length: 5697576 },
  700: { faceName: 'NotoSansJP', weight: 700, hash: 'eee16e4913b766be0eb7b9a02cd6ec3daf27292ca0ddf194cae01279aac1c9d0', length: 5698756 },
  800: { faceName: 'NotoSansJP', weight: 800, hash: '68d3c7136501158a6cf7d15c1c13e4af995aa164e34d1c250c3eef259cda74dd', length: 5696016 },
  900: { faceName: 'NotoSansJP', weight: 900, hash: '6ff9b55a270592e78670f98a2f866f621d05b6e1c3a18a14301da455a36f6561', length: 5693644 },
};

export const notoSansKr: WeightTable = {
  100: { faceName: 'NotoSansKR', weight: 100, hash: '302d55d333b15473a5b4909964ad17885a53cb41c34e3b434471f22ea55faea1', length: 6177560 },
  200: { faceName: 'NotoSansKR', weight: 200, hash: '1b03f89eccef4f2931d49db437091de1b15ced57186990749350a2cec1f4feb8', length: 6177360 },
  300: { faceName: 'NotoSansKR', weight: 300, hash: 'f8ed45f767a44de83d969ea276c3b4419c41a291d8460c32379e95930eae878e', length: 6175264 },
  400: { faceName: 'NotoSansKR', weight: 400, hash: '82547e25c2011910dae0116ba57d3ab9abd63f4865405677bd6f79c64487ae31', length: 6169044 },
  500: { faceName: 'NotoSansKR', weight: 500, hash: 'f67bdb1581dbb91b1ce92bdf89a0f3a4ca2545d821d204b17c5443bcda6b3677', length: 6166588 },
  600: { faceName: 'NotoSansKR', weight: 600, hash: '922e269443119b1ffa72c9631d4c7dcb365ab29ba1587b96e715d29c9a66d1b4', length: 6165240 },
  700: { faceName: 'NotoSansKR', weight: 700, hash: 'ed93ef6659b28599d47e40d020b9f55d18a01d94fdd43c9c171e44a66ddc1d66', length: 6165036 },
  800: { faceName: 'NotoSansKR', weight: 800, hash: 'e7088e3dfcc13f400aa9433a4042fce57b3dbe41038040073e9b5909a9390048', length: 6164096 },
  900: { faceName: 'NotoSansKR', weight: 900, hash: '14c5cfe30331277d21fa0086e66e11a7c414d4a5ce403229bdb0f384d3376888', length: 6163040 },
};

export const notoSansThai: WeightTable = {
  100: { faceName: 'NotoSansThai', weight: 100, hash: '77e781c33ba38f872109864fcf2f7bab58c7f85d73baf213fbcf7df2a7ea6b3f', length: 45684 },
  200: { faceName: 'NotoSansThai', weight: 200, hash: 'c8dc3faea7ead6f573771d50e3d2cc84b49431295bde43af0bd5f6356a628f72', length: 45792 },
  300: { faceName: 'NotoSansThai', weight: 300, hash: '9a1ba366a64ee23d486f48f0a276d75baef6432da4db5efb92f7c9b35dd5198d', length: 45728 },
  400: { faceName: 'NotoSansThai', weight: 400, hash: '5f71b18a03432951e2bce4e74497752958bd8c9976be06201af5390d47922be3', length: 45636 },
  500: { faceName: 'NotoSansThai', weight: 500, hash: '4c82507facc222df924a0272cda2bfdddc629de12b5684816aea0eb5851a61a7', length: 45720 },
  600: { faceName: 'NotoSansThai', weight: 600, hash: 'e81c6d83f8a625690b1ecc5de4f6b7b66a4d2ee9cbaf5b4f9ede73359c1db064', length: 45732 },
  700: { faceName: 'NotoSansThai', weight: 700, hash: '81bba197f8c779233db14166526e226f68e60cd9e33f2046b80f8075158cb433', length: 45640 },
  800: { faceName: 'NotoSansThai', weight: 800, hash: '7ae7ca1dae7a3df8e839ae08364e14e8e015337bab7dc2842abfc3315e477404', length: 45704 },
  900: { faceName: 'NotoSansThai', weight: 900, hash: '689d439d52c795a225c7fe4657a1072151407a86cc2910a51280337b8b1f57a3', length: 45584 },
};

export const notoSansHebrew: WeightTable = {
  100: { faceName: 'NotoSansHebrew', weight: 100, hash: '724a57dd8003a31bad4428c37d10b2777cec5b5bfd20c6ed1be44d265989b599', length: 46472 },
  200: { faceName: 'NotoSansHebrew', weight: 200, hash: 'ee40f0088e4408bd36620fd1fa7290fa145bf8964d2368aa181794e5b17ad819', length: 46532 },
  300: { faceName: 'NotoSansHebrew', weight: 300, hash: '5686c511d470cd4e52afd09f7e1f004efe33549ff0d38cb23fe3621de1969cc9', length: 46488 },
  400: { faceName: 'NotoSansHebrew', weight: 400, hash: '95e23e29b8422a9a461300a8b8e97630d8a2b8de319a9decbf53dc51e880ac41', length: 46476 },
  500: { faceName: 'NotoSansHebrew', weight: 500, hash: '7fa6696c1d7d0d7f4ac63f1c5dafdc52bf0035a3d5b63a181b58e5515af338f6', length: 46652 },
  600: { faceName: 'NotoSansHebrew', weight: 600, hash: 'cc6deb0701c8034e8ca4eb52ad13770cbe6e494a2bedb91238ad5cb7c591f0ae', length: 46648 },
  700: { faceName: 'NotoSansHebrew', weight: 700, hash: 'fbb2c56fd00f54b81ecb4da7033e1729f1c3fd2b14f19a15db35d3f3dd5aadf9', length: 46440 },
  800: { faceName: 'NotoSansHebrew', weight: 800, hash: '0fb06ecce97f71320c91adf9be6369c8c12979ac65d229fa7fb123f2476726a1', length: 46472 },
  900: { faceName: 'NotoSansHebrew', weight: 900, hash: '8638b2f26a6e16bacf0b34c34d5b8a62efa912a3a90bfb93f0eb25a7b3f8705e', length: 46372 },
};

export const notoSansArabic: WeightTable = {
  100: { faceName: 'NotoSansArabic', weight: 100, hash: '6cf2614bfc2885011fd9d47b2bcc7e5a576b3e35d379d4301d8247683a680245', length: 162152 },
  200: { faceName: 'NotoSansArabic', weight: 200, hash: 'cecf509869241973813ea04cf6c437ff1e571722fcd54e329880185baf750b19', length: 162412 },
  300: { faceName: 'NotoSansArabic', weight: 300, hash: 'c5219bd6425340861eb21a05d40d54da31875cb534dd128d5799b6b83674b9d1', length: 162324 },
  400: { faceName: 'NotoSansArabic', weight: 400, hash: '25c2bf5bc8222800e2d8887c3af985f61d5803177bd92b355cb8bffa09c48862', length: 161592 },
  500: { faceName: 'NotoSansArabic', weight: 500, hash: '47f226b1505792703ac273600be1dbce8c3cc83cd1981b3db5ef15e0f09bdd8a', length: 162156 },
  600: { faceName: 'NotoSansArabic', weight: 600, hash: '332c2d597ed4d1f4d1ed84ed493a341cf81515f5e4d392789a4764e084ff4f1f', length: 162512 },
  700: { faceName: 'NotoSansArabic', weight: 700, hash: '9235e0a73b449ef9a790df7bf5933644ede59c06099f7e96d8cda26c999641cd', length: 162268 },
  800: { faceName: 'NotoSansArabic', weight: 800, hash: '3614725eeafdb55d8eeabb81fb6fb294a807327fa01c2230b4e074f56922d0b5', length: 162896 },
  900: { faceName: 'NotoSansArabic', weight: 900, hash: 'cdbb85b809be063fb065f55b7226dc5161f4804795be56e007d7d3ce70208446', length: 162668 },
};

export const notoSerif: WeightTable = {
  100: { faceName: 'NotoSerif', weight: 100, hash: '7fd15a02691cfb99c193341bbb082778b1f3ca27e15fdcb7076816591994b7c7', length: 452700 },
  200: { faceName: 'NotoSerif', weight: 200, hash: '9446cf19cd57af964054d0afd385b76f9dec5e3b927c74a2d955041f97fad39b', length: 453240 },
  300: { faceName: 'NotoSerif', weight: 300, hash: '384650b173fced05061be4249607b7caedbc6ba463724075c3ede879ee78d456', length: 453240 },
  400: { faceName: 'NotoSerif', weight: 400, hash: 'b7373b9f9dab0875961c5d214edef00a9384ab593cde30c6462d7b29935ef8b2', length: 452276 },
  500: { faceName: 'NotoSerif', weight: 500, hash: '105a9e9c9bb80bcf8f8c408ed3473f1d9baad881686ea4602ecebebf22bbed50', length: 453160 },
  600: { faceName: 'NotoSerif', weight: 600, hash: '30257a49c70dd2e8abe6cc6a904df863dbc6f9ccf85f4b28a5c858aaa258eab6', length: 453104 },
  700: { faceName: 'NotoSerif', weight: 700, hash: 'dad0f53be4da04bfb608c81cfb72441fba851b336b2bd867592698cfaa2a0c3c', length: 452576 },
  800: { faceName: 'NotoSerif', weight: 800, hash: '12c5c47e6810fc5ea4291b6948adfba87c366eb3c081d66c99f989efd2b55975', length: 454040 },
  900: { faceName: 'NotoSerif', weight: 900, hash: '16f59df53d64f8a896e3dcacadc5b78e8b5fb503318bf01d9ddbe00e90dcceea', length: 453924 },
};

export const notoSerifItalic: WeightTable = {
  100: { faceName: 'NotoSerif-Italic', weight: 100, hash: '98c7bc89a0eca32e9045076dd4557dadf866820b3faf5dffe946614cd59bdbb8', length: 479008 },
  200: { faceName: 'NotoSerif-Italic', weight: 200, hash: '24a3e4603729024047e3af2a77e85fd3064c604b193add5b5ecb48fdeb630f4e', length: 479532 },
  300: { faceName: 'NotoSerif-Italic', weight: 300, hash: '940fb65bf51f2a2306bc12343c9661aa4309634ea15bf2b1a0c8da2d23e9e9f3', length: 479180 },
  400: { faceName: 'NotoSerif-Italic', weight: 400, hash: '65aae32ed0a63e3f6ce0fcde1cd5d04cd179699f7e1fef0d36a24948a3b17ce3', length: 477448 },
  500: { faceName: 'NotoSerif-Italic', weight: 500, hash: '322ec18ea04041aabc9f9b3529ff23e7d4e4e18d4330d39d4d422058c66ddded', length: 478256 },
  600: { faceName: 'NotoSerif-Italic', weight: 600, hash: '77e9996939afbc0723270879a0754de4374091b9b856f19790c098292992859c', length: 478316 },
  700: { faceName: 'NotoSerif-Italic', weight: 700, hash: 'b4cf981f0033c2e3d72585d84de3980bdfb87eaa4fe1d95392025ecd0fe0b83c', length: 477644 },
  800: { faceName: 'NotoSerif-Italic', weight: 800, hash: 'a9d0052ceaeea5a1962b7b1a23d995e39dd299ae59cfc288d3e9a68f1bf002e7', length: 478924 },
  900: { faceName: 'NotoSerif-Italic', weight: 900, hash: '99f429bfa3aea82cc9620a6242992534d8c7b10f75d0ec7ca15e1790ca315de7', length: 478760 },
};

export const notoSerifSc: WeightTable = {
  200: { faceName: 'NotoSerifSC', weight: 200, hash: '288d1ce3098084328c59b62c0ee3ae79a41f2c29eef8c0b2ba9384c2c18f41ed', length: 14778664 },
  300: { faceName: 'NotoSerifSC', weight: 300, hash: '7725ad7c403a2d10fd0fe29ae5d50445057a3559c348d67f129d0c9b8521bce8', length: 14780440 },
  400: { faceName: 'NotoSerifSC', weight: 400, hash: 'a17a0dbf1d43a65b75ebd0222a6aa4e6a6fb68f8ecc982c05c9584717ed3567f', length: 14781184 },
  500: { faceName: 'NotoSerifSC', weight: 500, hash: '6a74a2bb8923bef7e34b0436f0edd9ab03e3369fdeabb41807b820e6127fa4e6', length: 14781200 },
  600: { faceName: 'NotoSerifSC', weight: 600, hash: 'ebbd878444e9c226709d1259352d9d821849ee8105b5191d44101889603e154b', length: 14780624 },
  700: { faceName: 'NotoSerifSC', weight: 700, hash: 'bf6e98a81314a396a59661bf892ac872a9338c1b252845bec5659af39ca2304f', length: 14780140 },
  800: { faceName: 'NotoSerifSC', weight: 800, hash: '13be96afae56fd632bbf58ec62eb7b295af62fb6c7b3e16eff73748f0e04daf9', length: 14780920 },
  900: { faceName: 'NotoSerifSC', weight: 900, hash: 'e50e6bffa405fcb45583a0f40f120e1c158b83b4a17fae29bbe2359d36a5b831', length: 14780544 },
};

export const notoSerifTc: WeightTable = {
  200: { faceName: 'NotoSerifTC', weight: 200, hash: '7d21dcf9bae351366c21de7a554917af318fdf928b5f17a820b547584ebd3b03', length: 9926428 },
  300: { faceName: 'NotoSerifTC', weight: 300, hash: '2816a6528f03c7c7364da893e52ee3247622aa67efd5b96fac5c800af0cf7cfd', length: 9928912 },
  400: { faceName: 'NotoSerifTC', weight: 400, hash: '33247894b46a436114cb173a756d5f5a698f485c9cd88427a50c72301a81282f', length: 9930576 },
  500: { faceName: 'NotoSerifTC', weight: 500, hash: '3b3fa68244c613cee26f10dae75f702d5c61908973a763f2a87a4d3c9c14298a', length: 9932116 },
  600: { faceName: 'NotoSerifTC', weight: 600, hash: '1251e0304fa33bbf5c44cb361a0a969f998af22377a7b8e0bd9e862cf6c45d76', length: 9932824 },
  700: { faceName: 'NotoSerifTC', weight: 700, hash: 'db3ce7ba3443c00e9ff3ba87ebc51838598cb44bc25ea946480f2aebd290ad0e', length: 9933360 },
  800: { faceName: 'NotoSerifTC', weight: 800, hash: '96de55c76632a173cbb6ec9224dbd3040fa75234fadee1d7d03b081debbbdd37', length: 9933988 },
  900: { faceName: 'NotoSerifTC', weight: 900, hash: '2b58e95c7c7a35311152cb28da071dd10a156c30b1cfde117bac68cdca4984ea', length: 9934072 },
};

export const notoSerifJp: WeightTable = {
  200: { faceName: 'NotoSerifJP', weight: 200, hash: '320e653bbc19e207ade23a39d4896aee4424d85e213f6c3f05584d1dc358eaf3', length: 7999636 },
  300: { faceName: 'NotoSerifJP', weight: 300, hash: 'b01bd95435bede8e6e55adde97d61d85cf3cad907a8e5e21df3fdee97436c972', length: 8000752 },
  400: { faceName: 'NotoSerifJP', weight: 400, hash: '100644e0b414be1c2b1f524e63cb888a8ca2a29c59bc685b1d3a1dccdb8bef3d', length: 8000776 },
  500: { faceName: 'NotoSerifJP', weight: 500, hash: '7f2c9f09930f9571d72946c4836178d99966b6e3dae4d0fb6a39d9278a1979e7', length: 7999616 },
  600: { faceName: 'NotoSerifJP', weight: 600, hash: '53bcadccd57b01926f9da05cb4c3edf4a572fe9918d463b16ce2c8e76adcc059', length: 7997840 },
  700: { faceName: 'NotoSerifJP', weight: 700, hash: 'afcb90bae847b37af92ad759d2ed65ab5691eb6f76180a9f3f3eae9121afc30c', length: 7995008 },
  800: { faceName: 'NotoSerifJP', weight: 800, hash: '6341d1d0229059ed23e9f8293d29052cdc869a8a358118109165e8979c395342', length: 7994148 },
  900: { faceName: 'NotoSerifJP', weight: 900, hash: 'cb22da84d7cef667d91b79672b6a6457bcb22c9354ad8e96184a558a1eeb5786', length: 7992068 },
};

export const notoSerifKr: WeightTable = {
  200: { faceName: 'NotoSerifKR', weight: 200, hash: '54ba0237db05724a034c17d539fb253d29059dcb908cfc953c93b3e0d9de8197', length: 14020456 },
  300: { faceName: 'NotoSerifKR', weight: 300, hash: 'ae26b0d843cb7966777c3b764139d0de052c62e4bf52e47e24b20da304b17101', length: 14029668 },
  400: { faceName: 'NotoSerifKR', weight: 400, hash: '558c8dac58a96ed9bd55c0e3b605699b9ca87545eaba6e887bbf5c07a4e77e61', length: 14032260 },
  500: { faceName: 'NotoSerifKR', weight: 500, hash: 'f9534728d53d16ffa1e8a1382d95495e5ba8779be7cc7c70d2d40fff283bae93', length: 14041584 },
  600: { faceName: 'NotoSerifKR', weight: 600, hash: 'c571b015c56cee39099f0aaeeece3b81c49a8b206dd2ab577c03ca6bd4e2a7bb', length: 14040680 },
  700: { faceName: 'NotoSerifKR', weight: 700, hash: 'f5397eff043cbe24929663e25ddb03a3b383195c8b877b6a4fcc48ecc8247002', length: 14038616 },
  800: { faceName: 'NotoSerifKR', weight: 800, hash: 'abb4439400202f9efd9863fad31138021b95a579acb4ae98516311da0bbae842', length: 14036636 },
  900: { faceName: 'NotoSerifKR', weight: 900, hash: '17b5842749bdec2f53cb3c0ccbe8292ddf025864e0466fad64ca7b96e9f7be06', length: 14031812 },
};

export const notoSerifThai: WeightTable = {
  100: { faceName: 'NotoSerifThai', weight: 100, hash: '5eb35c0094128d7d01680b8843b2da94cc9dc4da0367bd73d9067287b48cc074', length: 59812 },
  200: { faceName: 'NotoSerifThai', weight: 200, hash: '48d9621d9f86d32d042924a1dca011561a6e12bb6577ecf77737d966721c6f96', length: 59968 },
  300: { faceName: 'NotoSerifThai', weight: 300, hash: 'd7e9e8ab36992509761cfbb52a8ccc910571ef167bd2cf9a15b7e393185aeadf', length: 59908 },
  400: { faceName: 'NotoSerifThai', weight: 400, hash: '3b677be028abaef2960675aa839310cf8b76eb02dd776b005e535ce8fd7b0dba', length: 59668 },
  500: { faceName: 'NotoSerifThai', weight: 500, hash: '269e49f943f4d5e3caebf7d381eca11ec24a3179713e9fc9594664d29f00638b', length: 59904 },
  600: { faceName: 'NotoSerifThai', weight: 600, hash: 'c2f95d912f539a2afb1a4fcaff25b3cfec88ff80bab99abc18e7e2b8a2ed0371', length: 59844 },
  700: { faceName: 'NotoSerifThai', weight: 700, hash: '26cc8f7b7d541cc050522a077448d3069e480d35edbd314748ab819fbce36b12', length: 59760 },
  800: { faceName: 'NotoSerifThai', weight: 800, hash: 'c7bcf386351f299d1a0440e23d14334dd32fcc736451a25721557bb13bf7ee9d', length: 60072 },
  900: { faceName: 'NotoSerifThai', weight: 900, hash: '3700c400ed31b5a182e21b6269e583e7dff8b8e16400504a9979684488574efa', length: 60004 },
};

export const notoSerifHebrew: WeightTable = {
  100: { faceName: 'NotoSerifHebrew', weight: 100, hash: 'd53174aa0c8cd8df260a9004a3007e393160b062d50f775fecd519f057067cbd', length: 54652 },
  200: { faceName: 'NotoSerifHebrew', weight: 200, hash: 'd31e71918ab5ff0f0e030903449509e146010510779991a47d4a063373f14a7c', length: 54720 },
  300: { faceName: 'NotoSerifHebrew', weight: 300, hash: '7017169ff82520c5bf669e4ab770ca0804795609313ce54c8a29b66df36cd20a', length: 54804 },
  400: { faceName: 'NotoSerifHebrew', weight: 400, hash: '001e675f8528148912f3c8b4ce0f2e3d05c7d6ff0cbaa4c415df9301cfeec28e', length: 54612 },
  500: { faceName: 'NotoSerifHebrew', weight: 500, hash: '4927576763b95c2ed87e58dbef8ac565d8054f419a4641d2eb6bb59afd498e6c', length: 54704 },
  600: { faceName: 'NotoSerifHebrew', weight: 600, hash: 'fd86539b46574a35e1898c62c3e30ff092e1b6588a36660bcf1e91845be1e36a', length: 54712 },
  700: { faceName: 'NotoSerifHebrew', weight: 700, hash: 'eb9fd16284df252ac1e4c53c73617a8e027cf66425e197f39c4cc7e9773baf4a', length: 54632 },
  800: { faceName: 'NotoSerifHebrew', weight: 800, hash: 'cdbfc88d81100057725ac72b7b26cc125b718916102f9771adeeb1b8ab890c36', length: 54816 },
  900: { faceName: 'NotoSerifHebrew', weight: 900, hash: 'ec3cf5173830f6e5485ef7f012b9b8dd0603116b32021d000269bf3dd1f18324', length: 54744 },
};

export const notoNaskhArabic: WeightTable = {
  400: { faceName: 'NotoNaskhArabic', weight: 400, hash: 'a19b33c4365bbd6e3f3ac85864fb134e44358ad188c30a9d67d606685d5261da', length: 215356 },
  500: { faceName: 'NotoNaskhArabic', weight: 500, hash: 'd8639b9c7c51cc662e5cf98ab913988835ca5cfde7fdd6db376c6f39f4ac8ea8', length: 215768 },
  600: { faceName: 'NotoNaskhArabic', weight: 600, hash: '76501d5ae7dea1d55ded66269abc936ece44353e17a70473c64f7072c61d7e89', length: 215720 },
  700: { faceName: 'NotoNaskhArabic', weight: 700, hash: 'bb9d4b9c041d13d8bc2c01fa6c5a4629bb4d19a158eec78a8249420a59418aa4', length: 215344 },
};

