import type { PdfAnnotationSpec } from '@pdfrx/engine';
import type { PagePlacement } from '@pdfrx/viewer-core';

/** Reference to immutable raster bytes stored through the relay's HTTP source endpoint. */
export interface SharedAnnotationImageSource {
  readonly documentId: string;
  readonly width: number;
  readonly height: number;
}

/** Serializable annotation state used by the collaboration protocol. */
export type SharedAnnotationSpec = Omit<PdfAnnotationSpec, 'appearanceImage'> & {
  /** Inline pixels retained for backwards compatibility with older relays. */
  readonly appearanceImage?: PdfAnnotationSpec['appearanceImage'];
  /** Preferred out-of-band storage for a raster appearance. */
  readonly appearanceImageSource?: SharedAnnotationImageSource;
};

/** Add, replace, or remove one annotation addressed by stable page placement. */
/** @internal */
export interface SharedAnnotationUpdate {
  readonly type: 'update';
  readonly placementId: string;
  readonly id: string;
  readonly spec: SharedAnnotationSpec;
}

export type SharedAnnotationChange =
  | { readonly type: 'add'; readonly placementId: string; readonly id: string; readonly spec: SharedAnnotationSpec }
  | SharedAnnotationUpdate
  | { readonly type: 'remove'; readonly placementId: string; readonly id: string };

/** Current materialized state of one shared annotation. */
export interface SharedAnnotationRecord {
  /** Stable virtual-page placement containing the annotation. */
  readonly placementId: string;
  /** PDF annotation `/NM` identity, unique within the placement. */
  readonly id: string;
  /** Serializable annotation geometry, content, and appearance properties. */
  readonly spec: SharedAnnotationSpec;
}

/** Authoritative annotation state, versioned independently from page operations. */
export interface AnnotationSessionSnapshot {
  /** Last committed annotation-operation revision. */
  readonly revision: number;
  /** Materialized annotation records present at this revision. */
  readonly annotations: readonly SharedAnnotationRecord[];
}

/** Optimistic annotation operation submitted to an authoritative relay. */
export interface AnnotationOperationRequest {
  /** Unique correlation id generated by the submitting client. */
  readonly operationId: string;
  /** Stable participant id responsible for the change. */
  readonly actorId: string;
  /** Annotation revision observed before submitting the change. */
  readonly baseRevision: number;
  /** Requested annotation mutation. */
  readonly change: SharedAnnotationChange;
}

/** Accepted annotation operation with its authoritative sequence number. */
export interface CommittedAnnotationOperation extends AnnotationOperationRequest {
  /** Revision assigned by the relay. */
  readonly revision: number;
}

/** @internal Non-persistent annotation geometry broadcast while a participant drags. */
export interface AnnotationPreview {
  readonly actorId: string;
  readonly changes: readonly SharedAnnotationUpdate[];
}

/**
 * Validates and commits an annotation operation against authoritative state.
 * @throws {@link AnnotationProtocolError} for a stale revision or missing placement.
 */
export function commitAnnotationOperation(
  snapshot: AnnotationSessionSnapshot,
  pages: readonly PagePlacement[],
  request: AnnotationOperationRequest,
): { readonly snapshot: AnnotationSessionSnapshot; readonly committed: CommittedAnnotationOperation } {
  if (request.baseRevision !== snapshot.revision) {
    throw new AnnotationProtocolError('annotation-revision-mismatch', `Expected annotation revision ${snapshot.revision}, got ${request.baseRevision}`);
  }
  if (!pages.some((page) => page.placementId === request.change.placementId)) {
    throw new AnnotationProtocolError('placement-not-found', `Page placement not found: ${request.change.placementId}`);
  }
  const annotations = snapshot.annotations.filter(
    (item) => item.placementId !== request.change.placementId || item.id !== request.change.id,
  );
  if (request.change.type !== 'remove') {
    const previous = snapshot.annotations.find(
      (item) => item.placementId === request.change.placementId && item.id === request.change.id,
    );
    annotations.push({
      placementId: request.change.placementId,
      id: request.change.id,
      spec: request.change.type === 'update' && previous
        ? { ...previous.spec, ...request.change.spec }
        : request.change.spec,
    });
  }
  const revision = snapshot.revision + 1;
  return { snapshot: { revision, annotations }, committed: { ...request, revision } };
}

/**
 * Applies the next committed annotation event to a client-side snapshot.
 * @throws {@link AnnotationProtocolError} when a revision is skipped or replayed.
 */
export function applyCommittedAnnotationOperation(
  snapshot: AnnotationSessionSnapshot,
  committed: CommittedAnnotationOperation,
): AnnotationSessionSnapshot {
  if (committed.revision !== snapshot.revision + 1 || committed.baseRevision !== snapshot.revision) {
    throw new AnnotationProtocolError('unexpected-annotation-revision', `Unexpected annotation revision ${committed.revision}`);
  }
  const annotations = snapshot.annotations.filter(
    (item) => item.placementId !== committed.change.placementId || item.id !== committed.change.id,
  );
  if (committed.change.type !== 'remove') {
    const previous = snapshot.annotations.find(
      (item) => item.placementId === committed.change.placementId && item.id === committed.change.id,
    );
    annotations.push({
      placementId: committed.change.placementId,
      id: committed.change.id,
      spec: committed.change.type === 'update' && previous
        ? { ...previous.spec, ...committed.change.spec }
        : committed.change.spec,
    });
  }
  return { revision: committed.revision, annotations };
}

/** Protocol validation error carrying a machine-readable relay error code. */
export class AnnotationProtocolError extends Error {
  /** Creates an annotation protocol failure with a relay-safe error code. */
  constructor(readonly code: string, message: string) {
    super(message);
    this.name = 'AnnotationProtocolError';
  }
}
