import type { PdfFormFieldValue } from '@pdfrx/engine';
import type { PagePlacement } from '@pdfrx/viewer-core';

/** Value update for a form field owned by an immutable source document. */
export interface SharedFormFieldChange {
  /** Session-level id of the source PDF containing the field. */
  readonly documentId: string;
  /** Fully-qualified AcroForm field name inside that source PDF. */
  readonly fieldName: string;
  /** New field value, retaining scalar, boolean, or multi-select shape. */
  readonly value: PdfFormFieldValue;
}

/** Materialized shared value for one source-scoped AcroForm field. */
export interface SharedFormFieldRecord extends SharedFormFieldChange {}

/** Authoritative form state, versioned independently from pages and annotations. */
export interface FormSessionSnapshot {
  /** Last committed form-operation revision. */
  readonly revision: number;
  /** Latest materialized value for every changed field. */
  readonly fields: readonly SharedFormFieldRecord[];
}

/** Optimistic form operation submitted to an authoritative relay. */
export interface FormOperationRequest {
  /** Unique correlation id generated by the submitting client. */
  readonly operationId: string;
  /** Stable participant id responsible for the update. */
  readonly actorId: string;
  /** Form revision observed before submitting the update. */
  readonly baseRevision: number;
  /** Requested source-scoped field update. */
  readonly change: SharedFormFieldChange;
}

/** Accepted form operation with its authoritative sequence number. */
export interface CommittedFormOperation extends FormOperationRequest {
  /** Revision assigned by the relay. */
  readonly revision: number;
}

/**
 * Validates and commits a form update against authoritative state.
 * @throws {@link FormProtocolError} for a stale revision or unknown source document.
 */
export function commitFormOperation(
  snapshot: FormSessionSnapshot,
  pages: readonly PagePlacement[],
  request: FormOperationRequest,
): { readonly snapshot: FormSessionSnapshot; readonly committed: CommittedFormOperation } {
  if (request.baseRevision !== snapshot.revision) {
    throw new FormProtocolError('form-revision-mismatch', `Expected form revision ${snapshot.revision}, got ${request.baseRevision}`);
  }
  if (!pages.some((page) => page.source.documentId === request.change.documentId)) {
    throw new FormProtocolError('document-not-found', `Document source not found: ${request.change.documentId}`);
  }
  const fields = snapshot.fields.filter(
    (field) => field.documentId !== request.change.documentId || field.fieldName !== request.change.fieldName,
  );
  fields.push(request.change);
  const revision = snapshot.revision + 1;
  return { snapshot: { revision, fields }, committed: { ...request, revision } };
}

/**
 * Applies the next committed form event to a client-side snapshot.
 * @throws {@link FormProtocolError} when a revision is skipped or replayed.
 */
export function applyCommittedFormOperation(
  snapshot: FormSessionSnapshot,
  committed: CommittedFormOperation,
): FormSessionSnapshot {
  if (committed.revision !== snapshot.revision + 1 || committed.baseRevision !== snapshot.revision) {
    throw new FormProtocolError('unexpected-form-revision', `Unexpected form revision ${committed.revision}`);
  }
  const fields = snapshot.fields.filter(
    (field) => field.documentId !== committed.change.documentId || field.fieldName !== committed.change.fieldName,
  );
  fields.push(committed.change);
  return { revision: committed.revision, fields };
}

/** Protocol validation error carrying a machine-readable relay error code. */
export class FormProtocolError extends Error {
  /** Creates a form protocol failure with a relay-safe error code. */
  constructor(readonly code: string, message: string) {
    super(message);
    this.name = 'FormProtocolError';
  }
}
